symfony:
  extends:
    file: common.yml
    service: symfony
  container_name: finalrunner_symfony_prod
  ports:
    - 8888:8888
  environment:
    SYMFONY_ENV: prod
    FAKETIME: +0d
    LD_PRELOAD: /usr/local/lib/faketime/libfaketime.so.1

nginx:
  extends:
    file: common.yml
    service: nginx
  container_name: finalrunner_nginx_prod
  restart: always
  links:
    - fpm
  volumes:
    - ./nginx/nginx_production.conf:/etc/nginx/conf.d/default.conf
  environment:
    VIRTUAL_HOST: staging.finalrunner.com


fpm:
  extends:
    file: common.yml
    service: fpm
  restart: always
  container_name: finalrunner_fpm_prod
  command: php-fpm --allow-to-run-as-root
  volumes:
    - ./php/xdebug_prod.ini:/usr/local/etc/php/conf.d/xdebug.ini
    - ./php/fpm_prod.conf:/usr/local/etc/php-fpm.conf
  volumes_from:
    - symfony
