services:
#    spectate.example:
#        class: SpectateBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    spectate.admin.spectate:
        class: SpectateBundle\Admin\SpectateAdmin
        arguments: [~, SpectateBundle\Entity\Spectate, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Spectate }

    spectate.admin.reprezentation:
        class: SpectateBundle\Admin\ReprezentationAdmin
        arguments: [~, SpectateBundle\Entity\Reprezentation, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Reprezentation }
