<?php

namespace SpectateBundle\Repository;

/**
 * ReprezentationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReprezentationRepository extends \Doctrine\ORM\EntityRepository
{
}
