<?php

namespace SpectateBundle\Repository;

/**
 * SpectateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpectateRepository extends \Doctrine\ORM\EntityRepository
{
}
