UserBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
        lastName:
            type: string
            length: 255
        contactNumber:
            type: string
            length: 255
    oneToMany:
        reservations:
            targetEntity: RezervationBundle\Entity\Rezervation
            mappedBy: user
    # manyToMany:
    #     spectate:
    #         targetEntity: SpectateBundle\Entity\Spectate
    #         mappedBy: users
    #         
    lifecycleCallbacks: {  }
