UserBundle\Entity\User:
    properties:
        firstName:
            - NotBlank:
                message: 'Please enter a first name'
        lastName:
            - NotBlank:
                message: 'Please enter a last name'
        contactNumber:
            - NotBlank:
                message: 'Please enter a contact number'
UserBundle\Entity\Contact:
    properties:
        name:
            - NotBlank:
                message: 'Please enter your name'
        content:
            - NotBlank:
                message: 'Please enter your message'
        email:
            - Email:
                message: 'Please enter a valid email address'