<?php

namespace RezervationBundle\Repository;

/**
 * RezervationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RezervationRepository extends \Doctrine\ORM\EntityRepository
{
}
