rezervation_routing:
    resource: "@RezervationBundle/Resources/config/routing/rezervation.yml"
    prefix:   /reservation/

reservation_make:
    path:     /spectate/reservation
    defaults: { _controller: RezervationBundle:Rezervation:rezervation }