services:
#    rezervation.example:
#        class: RezervationBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    rezervation.form.type:
        class: RezervationBundle\Form\RezervationFormType
        arguments: ["@security.token_storage","@doctrine.orm.entity_manager" ]
        tags:
          - { name: form.type, alias: rezervation_form_type }

    # rezervation.form.event.listener:
    #     class: RezervationBundle\EventListener\SpectateListener
    #     arguments: ["@doctrine.orm.entity_manager" ]
    #     tags:
    #       - { name: form.type, alias: spectate_listener }

    rezervation.admin.rezervation:
        class: RezervationBundle\Admin\RezervationAdmin
        arguments: [~, RezervationBundle\Entity\Rezervation, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Rezervation }
