SpectateBundle\Entity\Reprezentation:
    type: entity
    table: null
    repositoryClass: SpectateBundle\Repository\ReprezentationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        location:
            type: string
            length: 255
        date:
            type: datetime
        distribution:
            type: text
        numberOfSeats:
            type: integer
    manyToOne:
        spectate:
            targetEntity: SpectateBundle\Entity\Spectate
            joinColumn:
                name: spectate_id
                referencedColumnName: id
            cascade: ['persist']
    lifecycleCallbacks: {  }
